### ISSUE TITLE
[Feature Request / 功能需求]节点资源占用情况

### ISSUE THREAD

**Issue by Aaroncao7** [WhiteMatrixTech/experimental-cloud-front#1]
**Describe the expected state / 描述期望**
需要在弹性云服务器管理>资源使用情况页面中将grafana的节点资源占用情况页面嵌入前端。
**Additional context / 附加信息**

**Comment by Aaroncao7** [comment]
http://8.142.34.146:9000/d/BlEbbDrGk/docker-monitoring-with-node-selection?orgId=1&refresh=10s

**Comment by Liyw-liyw** [comment]
> **Describe the expected state / 描述期望**
> 需要在弹性云服务器管理>资源使用情况页面中将grafana的节点资源占用情况页面嵌入前端。
> **Additional context / 附加信息**

弹性云列表栏变更：
1. 点击  实例数据  ，查看节点实例情况
2. 点击 资源使用情况 ， 查看grafana的相关资源占用情况
